language: ruby
rvm:
- 2.2.3
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: g5gzRTskyI74DTXb99k2NUBSFy1PXrBMv117F5ir2TE6FSf+Y6Q7MRH6140QfsXTmMsTXQGp6NPQki8GcSgjo8DCXvw9Dy1uKBfMhdDUICisTjwTDMEce+iOukE1Jp93VzhntEwWpiTNgljeACBVhnIa0HB8F+v+VfKBvZzEWxWv1XRY0fd2b1qYU9NAWJUuGZ8jMvGux61CtoLpmOkOnQs+FYRKZQWsYlWvoBUzj5oYb6pJ9GAg9aT6Z8G46xvaHdkD/MsZHnuiwfYhvuUcGCxLCz/vOR22F+pMYaX0+VhzoCUyqqnpYnbX+IO8LhYst1CZVK4GIZFCPt7q5bCALmLM5AiTEvZ5uClzpO7KcnpOqgQ9ppK4IOWmCfGzCYsKCSh/J6SU/Ez4YE9ZIfj801McBoZyEjXqr6K3I/ZHK55Yz79TWPd+1lEjVI1ePIqqHG9q6rgG8l0U4ciylRfMqBEmGor6QFhTzQ6b2SmBPatTTDLq5gF0EBM4blBvWyIME0Sy5J0iGF9nZlD+FVyNUiJ3CUKZOAwd4bejASVqP/kcuMKvDTqDPcMX3vm6rkWb19cLWcMH04vg9xIJo6UPS/ZuGsOtP/gz9QUy+wogZOirikMkq1TKsnN/WEBrswJEgY55B+WGGH6S/t3hEQR46+ze6JvYb9St3XBLPqKYiRc=
  app: nameless-waters-21016
  on:
    repo: Tontsu/ratebeer
